name: hoge

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.x

jobs:
  on_push_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
